name: scae
dependencies:
  - python=3.9
  - pip=20.2.4
  - pip:
    - easydict==1.9
    - torch==1.7.1
    - torchvision==0.8.2
    - pytorch_lightning==1.1.1
    - torch-optimizer==0.0.1a17
    - scipy==1.5.4
    - wandb==0.10.12
    - jsonschema==3.2.0
    - jsonargparse==3.3.1
# jsonpatch==1.26
# jsonpointer==2.0
# json5==0.9.5