# Universal configs like logging, data directory, etc
non_deterministic: False
debug: False

data_workers: 8

log:
  run_name:
  project: StackedCapsuleAutoEncoders
  team: mlatberkeley
  upload: True
  frequency: 10
