# Experiment-set specific configs
batch_size: 500
num_epochs: 300

model: pcae
dataset: mnist

pcae:
  num_caps: 16
  caps_dim: 6
  feat_dim: 16

  optimizer: radam
  lr: 0.01
  lr_decay: 0.998
  lr_restart_interval: 4000
  lr_scheduler: cosrestarts

  weight_decay: 0.0
  loss_ll_coeff: 1.0
  loss_temp_l1_coeff: 0.01
  loss_mse_coeff: 0.0

  encoder:
    noise_scale: 4.
    inverse_space_transform: True

  decoder:
    alpha_channel: False
    template_nonlin: sigmoid
    color_nonlin: sigmoid
    template_size: [11, 11]
    output_size: [40, 40]
    lr_coeff: 1.0

ocae:
  lr: 0.1


